SCRIPTS = (
    "bower/marked/marked.min.js", "bower/moment/min/moment.min.js",
    "bower/moment-timezone/builds/moment-timezone-with-data.min.js",
    "bower/angular/angular.min.js",
    "bower/angular-animate/angular-animate.min.js",
    "bower/angular-aria/angular-aria.min.js",
    "bower/angular-material/angular-material.min.js",
    "bower/angular-route/angular-route.min.js",
    "bower/angular-sanitize/angular-sanitize.min.js",
    "bower/angular-marked/angular-marked.min.js",
    "bower/angular-moment/angular-moment.min.js",
    "bower/angulartics/dist/angulartics.min.js",
    "bower/angulartics/dist/angulartics-ga.min.js", 
    "bower/angular-jwt/dist/angular-jwt.min.js",
    "app.js", "routes.js",
    "controllers/error-ctrl.js", "controllers/home-ctrl.js",
    "controllers/page-ctrl.js", "controllers/sponsor-ctrl.js",
    "controllers/speakers/proposed-ctrl.js",
    "controllers/speakers/talk-detail-ctrl.js",
    "controllers/speakers/submit-talk-ctrl.js",
    "controllers/speakers/schedule-ctrl.js", "controllers/users/user-ctrl.js",
    "controllers/users/login-ctrl.js", "controllers/users/signup-ctrl.js",
    "controllers/users/talks-ctrl.js", "controllers/users/edit-talk-ctrl.js",
    "controllers/users/profile-ctrl.js", "controllers/users/verify-ctrl.js",
    "controllers/users/reset-password-ctrl.js", "controllers/blog/blog-ctrl.js",
    "services/api-factory.js",
    "services/storage-service.js",
    "directives/menu-widgets.js",
    )
